### ISSUE TITLE
Need more customization api/props about handler color

### ISSUE THREAD

**Issue by wynn5a** [susielu/react-annotation#21]
This is a wonderful tool for image annotation. 💯 

I have a problem that It is so hard to see those handlers when background color is grey, could u please add some props/api for its color?

It is difficult for me to change the source code because I am not a professional front-end developer. 😿

**Comment by susielu** [comment]
This is something that you can override with css: 
```css
.handle {
  stroke: "red",
  fill: "red",
  fill-opacity: .5;
}
```

Are you having issues with that?
